version: '3.8'

services:
  # 1. База данных (1 реплика на manager узле)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: autopark_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - autopark-overlay

  # 2. Redis (распределенный кэш)
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - autopark-overlay

  # 3. API сервис (2 реплики для кластера)
  api:
    image: autopark-api:latest
    environment:
      DATABASE_URL: postgresql://admin:${DB_PASSWORD:-admin123}@postgres:5432/autopark_db
      REDIS_URL: redis://redis:6379/0
    deploy:
      replicas: 2  # ← КЛАСТЕР из 2 контейнеров!
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - autopark-overlay
    depends_on:
      - postgres
      - redis

  # 4. Веб-панель (1 реплика)
  dashboard:
    image: autopark-dashboard:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - autopark-overlay

  # 5. Nginx с балансировкой нагрузки
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./nginx/nginx-swarm.conf
        target: /etc/nginx/nginx.conf
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - autopark-overlay
    depends_on:
      - api
      - dashboard

  # 6. Prometheus для мониторинга кластера
  prometheus:
    image: prom/prometheus:latest
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./monitoring/prometheus/prometheus-swarm.yml
        target: /etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - autopark-overlay

networks:
  autopark-overlay:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local